name: Build

on: [push]

jobs:
  build:
    runs-on: ${{matrix.platform.os}}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { os: windows-2022, config_preset: vs2022-amd64 }
        - { os: ubuntu-22.04, config_preset: gcc-amd64 }
        - { os: ubuntu-22.04, config_preset: clang-amd64 }
        - { os: macos-12,     config_preset: clang-amd64 }
        build_type: [release, debug]

    env:
      SOURCE_DIR: ${{github.workspace}}
      BUILD_DIR: ${{github.workspace}}/build/${{matrix.platform.config_preset}}

    steps:
    - name: Install ninja & cppcheck (Ubuntu)
      run: sudo apt-get update && sudo apt-get install ninja-build cppcheck -y
      if: matrix.platform.os == 'ubuntu-22.04'

    - name: Install ninja & brew llvm (MacOS)
      run: brew install ninja llvm
      if: matrix.platform.os == 'macos-12'

    - uses: actions/checkout@v2

    - name: Create Build Environment
      # We'll use this as our working directory for subsequent commands.
      run: cmake -E make_directory ${{env.BUILD_DIR}}

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system.
      shell: bash
      working-directory: ${{env.SOURCE_DIR}}
      run: cmake --preset ${{matrix.platform.config_preset}}

    - name: Build
      working-directory: ${{env.SOURCE_DIR}}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>".
      run: cmake --build --preset ${{matrix.platform.config_preset}}-${{matrix.build_type}}

    - name: Test
      working-directory: ${{env.BUILD_DIR}}
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{ matrix.build_type }}
